language: ruby
rvm:
  - 2.6
script:
  - jekyll build --drafts
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local-dir: _site
  - provider: rubygems
    api_key: $API_KEY
    skip-cleanup: true
    on:
      tags: true
